### PR TITLE
chore: add prettier config

### PR DESCRIPTION
**Pull request by volkanunsal**

### CODE REVIEW

**Comment by thantos** [comment]
You'll want to run `yarn default` to apply configuration changes locally.

Looks like you are just applying the defaults? With a `prettierrc.json` already generated, does this change change the formatting of any of the code.

**Comment by volkanunsal** [comment]
> Looks like you are just applying the defaults? With a prettierrc.json already generated, does this change change the formatting of any of the code.

This shouldn't change any of the code. Like you said, it's using the defaults, but it's necessary to generate a `.prettierrc.json` file because contributors may have user defaults that differ from the project defaults and if they also have "format on save" enabled, saving the file will cause massive diffs.

**Comment by thantos** [comment]
Not sure if you saw, but the main branch has a `prettierrc.json` now from #248 

After your suggestion and prettier supporting type 4.7, we cleaned up the config a bit.

**Comment by thantos** [comment]
Looks like projen doesn't even add the defaults to the `prettierrc`, I am fine with this change as it makes the configuration explicit.

**Comment by volkanunsal** [comment]
> Hard to discover. prettier: {} was enough to add the config file and wire up eslint.

How about using `prettier: true` instead? I think that config only needs a truthy value.

**Comment by volkanunsal** [comment]
In fact, that property expects a boolean... There is another property for adding options, per the type def. 

Screen Shot 2022-06-16 at 8 25 40 AM

It's weird that `{}` doesn't cause a type error...

**Pull request closed without merging**
