### PR TITLE
chore: [ignore-me] serialize PR with test run changes

### PR DESCRIPTION
**Pull request by thantos**
#402 on top of #510

### CODE REVIEW

**Comment by sam-goodwin** [comment]
Should we point this at my original PR and merge it?

**Comment by sam-goodwin** [comment]
I would like to see the changes between this and what's in mine. Merging against main makes that hard to see.

**Comment by sam-goodwin** [comment]
Oh never mind - I misunderstood the purpose of this change. Looks like closure serializer is stable. I have one more commit to make where I put the default serializer back to v1. Then I'll merge.

**Comment by thantos** [comment]
#402 has been updated with this change, closing.

**Pull request closed without merging**
